---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - name: install Homebrew packages
      homebrew:
        name: "{{item}}"
      with_items:
        - less
        - vim
        - binutils
        - binwalk
        - colordiff
        - coreutils
        - curl
        - direnv
        - docker
        - editorconfig
        - ffmpeg
        - fzf
        - gawk
        - gcc
        - gdb
        - geoip
        - gibo
        - git
        - git-extras
        - git-flow
        - gnu-sed
        - gnutls
        - go
        - highlight
        - htop
        - httpie
        - hub
        - imagemagick
        - jq
        - ktr0731/evans/evans
        - m-cli
        - neovim/neovim/neovim
        - nkf
        - nmap
        - node
        - noti
        - openssl
        - pstree
        - python
        - python3
        - reattach-to-user-namespace
        - redis
        - ripgrep
        - ruby
        - ruby-build
        - shellcheck
        - the_silver_searcher
        - tig
        - tmux
        - tree
        - wget
        - yarn
        - zsh
        - kubectl
        - trash
        - gcsfuse

    - name: install Homebrew Cask packages
      homebrew_cask:
        name: "{{item}}"
      with_items:
          - google-chrome
          - firefox
          - docker
          - iterm2
          - slack
          - xquartz
          - 1password
          - goland
          - webstorm
          - rocket
          - visual-studio-code
          - shiftit
          - kindle
          - atom
          - google-drive-file-stream
          - google-cloud-sdk
          - osxfuse

    - name: check zplug
      shell: type zplug
      register: has_zplug
      failed_when: false

    - name: install zplug
      shell: curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
      when: has_zplug == false
