#!/usr/bin/env bash

verbose='-vv'

set -e

# install Homebrew
yes "" | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install ansible

ansible-playbook "$verbose" site.yml
